# Generated by Django 4.0.3 on 2023-10-10 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'admin'), ('User', 'user')], default='User', max_length=5),
        ),
    ]
