# Generated by Django 4.0.3 on 2023-10-11 09:57

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='picture',
        ),
        migrations.AddField(
            model_name='books',
            name='file',
            field=models.FileField(blank=True, upload_to=books.models.Books.nameFile),
        ),
    ]
